-- Custodian Release 2/3: durable runtime and provenance tables.
--
-- This migration intentionally uses text columns with explicit checks rather
-- than PostgreSQL enum types. That keeps the API contracts inspectable and
-- makes future additive lifecycle values a deliberate migration decision.
-- Every public row is owner-scoped. The composite foreign keys are important:
-- a UUID alone is never enough to cross an owner, case, or run boundary.

create table if not exists public.entities (
  id uuid primary key default gen_random_uuid(),
  owner_id uuid not null references auth.users(id) on delete cascade,
  case_id uuid not null,
  entity_type text not null,
  canonical_key text not null default '',
  display_name text not null,
  description text not null default '',
  attributes jsonb not null default '{}'::jsonb,
  source_record_id uuid,
  provenance jsonb not null default '{}'::jsonb,
  lifecycle_status text not null default 'active',
  created_by uuid not null references auth.users(id),
  updated_by uuid not null references auth.users(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint entities_case_fk foreign key (owner_id, case_id)
    references public.cases (owner_id, id) on delete cascade,
  constraint entities_source_record_fk foreign key (owner_id, source_record_id)
    references public.records (user_id, id) on delete set null,
  constraint entities_entity_type_ck check (
    entity_type in ('person', 'organization', 'project', 'place', 'concept', 'artifact', 'event', 'system', 'other')
  ),
  constraint entities_canonical_key_length_ck check (char_length(canonical_key) <= 500),
  constraint entities_display_name_nonblank_ck check (btrim(display_name) <> ''),
  constraint entities_display_name_length_ck check (char_length(display_name) <= 500),
  constraint entities_description_length_ck check (char_length(description) <= 20000),
  constraint entities_attributes_object_ck check (jsonb_typeof(attributes) = 'object'),
  constraint entities_provenance_object_ck check (jsonb_typeof(provenance) = 'object'),
  constraint entities_lifecycle_status_ck check (lifecycle_status in ('active', 'merged', 'archived')),
  constraint entities_owner_id_unique unique (owner_id, id),
  constraint entities_owner_case_id_unique unique (owner_id, case_id, id)
);

create table if not exists public.entity_relations (
  id uuid primary key default gen_random_uuid(),
  owner_id uuid not null references auth.users(id) on delete cascade,
  case_id uuid not null,
  subject_entity_id uuid not null,
  object_entity_id uuid not null,
  relation_type text not null,
  confidence integer not null default 0,
  attributes jsonb not null default '{}'::jsonb,
  provenance jsonb not null default '{}'::jsonb,
  lifecycle_status text not null default 'active',
  created_by uuid not null references auth.users(id),
  updated_by uuid not null references auth.users(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint entity_relations_case_fk foreign key (owner_id, case_id)
    references public.cases (owner_id, id) on delete cascade,
  constraint entity_relations_subject_fk foreign key (owner_id, case_id, subject_entity_id)
    references public.entities (owner_id, case_id, id) on delete cascade,
  constraint entity_relations_object_fk foreign key (owner_id, case_id, object_entity_id)
    references public.entities (owner_id, case_id, id) on delete cascade,
  constraint entity_relations_not_self_ck check (subject_entity_id <> object_entity_id),
  constraint entity_relations_type_ck check (
    relation_type in ('supports', 'contradicts', 'depends_on', 'causes', 'caused_by', 'part_of', 'instance_of', 'mentions', 'related_to', 'supersedes', 'blocks', 'enables', 'same_as')
  ),
  constraint entity_relations_confidence_ck check (confidence between 0 and 100),
  constraint entity_relations_attributes_object_ck check (jsonb_typeof(attributes) = 'object'),
  constraint entity_relations_provenance_object_ck check (jsonb_typeof(provenance) = 'object'),
  constraint entity_relations_lifecycle_status_ck check (lifecycle_status in ('active', 'superseded', 'rejected', 'archived')),
  constraint entity_relations_owner_id_unique unique (owner_id, id),
  constraint entity_relations_owner_case_id_unique unique (owner_id, case_id, id),
  constraint entity_relations_pair_unique unique (owner_id, case_id, subject_entity_id, object_entity_id, relation_type)
);

create table if not exists public.experiments (
  id uuid primary key default gen_random_uuid(),
  owner_id uuid not null references auth.users(id) on delete cascade,
  case_id uuid not null,
  title text not null,
  hypothesis text not null,
  expected_observation text not null default '',
  design jsonb not null default '{}'::jsonb,
  result jsonb not null default '{}'::jsonb,
  status text not null default 'proposed',
  source_record_id uuid,
  provenance jsonb not null default '{}'::jsonb,
  lifecycle_status text not null default 'active',
  created_by uuid not null references auth.users(id),
  updated_by uuid not null references auth.users(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint experiments_case_fk foreign key (owner_id, case_id)
    references public.cases (owner_id, id) on delete cascade,
  constraint experiments_source_record_fk foreign key (owner_id, source_record_id)
    references public.records (user_id, id) on delete set null,
  constraint experiments_title_nonblank_ck check (btrim(title) <> ''),
  constraint experiments_title_length_ck check (char_length(title) <= 500),
  constraint experiments_hypothesis_nonblank_ck check (btrim(hypothesis) <> ''),
  constraint experiments_hypothesis_length_ck check (char_length(hypothesis) <= 20000),
  constraint experiments_expected_observation_length_ck check (char_length(expected_observation) <= 10000),
  constraint experiments_design_object_ck check (jsonb_typeof(design) = 'object'),
  constraint experiments_result_object_ck check (jsonb_typeof(result) = 'object'),
  constraint experiments_status_ck check (status in ('proposed', 'planned', 'running', 'completed', 'cancelled', 'inconclusive')),
  constraint experiments_provenance_object_ck check (jsonb_typeof(provenance) = 'object'),
  constraint experiments_lifecycle_status_ck check (lifecycle_status in ('active', 'superseded', 'archived')),
  constraint experiments_owner_id_unique unique (owner_id, id),
  constraint experiments_owner_case_id_unique unique (owner_id, case_id, id)
);

create table if not exists public.decision_reviews (
  id uuid primary key default gen_random_uuid(),
  owner_id uuid not null references auth.users(id) on delete cascade,
  case_id uuid not null,
  decision_record_id uuid,
  question text not null,
  criteria jsonb not null default '[]'::jsonb,
  options jsonb not null default '[]'::jsonb,
  recommendation text not null default '',
  decision text not null default '',
  rationale text not null default '',
  status text not null default 'draft',
  review_due_at timestamptz,
  provenance jsonb not null default '{}'::jsonb,
  lifecycle_status text not null default 'active',
  created_by uuid not null references auth.users(id),
  updated_by uuid not null references auth.users(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint decision_reviews_case_fk foreign key (owner_id, case_id)
    references public.cases (owner_id, id) on delete cascade,
  constraint decision_reviews_record_fk foreign key (owner_id, decision_record_id)
    references public.records (user_id, id) on delete set null,
  constraint decision_reviews_question_nonblank_ck check (btrim(question) <> ''),
  constraint decision_reviews_question_length_ck check (char_length(question) <= 20000),
  constraint decision_reviews_criteria_array_ck check (jsonb_typeof(criteria) = 'array' and jsonb_array_length(criteria) <= 100),
  constraint decision_reviews_options_array_ck check (jsonb_typeof(options) = 'array' and jsonb_array_length(options) <= 100),
  constraint decision_reviews_recommendation_length_ck check (char_length(recommendation) <= 10000),
  constraint decision_reviews_decision_length_ck check (char_length(decision) <= 10000),
  constraint decision_reviews_rationale_length_ck check (char_length(rationale) <= 20000),
  constraint decision_reviews_status_ck check (status in ('draft', 'open', 'decided', 'deferred', 'superseded', 'archived')),
  constraint decision_reviews_provenance_object_ck check (jsonb_typeof(provenance) = 'object'),
  constraint decision_reviews_lifecycle_status_ck check (lifecycle_status in ('active', 'superseded', 'archived')),
  constraint decision_reviews_owner_id_unique unique (owner_id, id),
  constraint decision_reviews_owner_case_id_unique unique (owner_id, case_id, id)
);

create table if not exists public.forecasts (
  id uuid primary key default gen_random_uuid(),
  owner_id uuid not null references auth.users(id) on delete cascade,
  case_id uuid not null,
  claim_id uuid,
  target text not null,
  horizon text not null,
  probability numeric(5, 4) not null,
  rationale text not null default '',
  outcome jsonb not null default '{}'::jsonb,
  status text not null default 'draft',
  resolved_at timestamptz,
  provenance jsonb not null default '{}'::jsonb,
  lifecycle_status text not null default 'active',
  created_by uuid not null references auth.users(id),
  updated_by uuid not null references auth.users(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint forecasts_case_fk foreign key (owner_id, case_id)
    references public.cases (owner_id, id) on delete cascade,
  constraint forecasts_claim_fk foreign key (owner_id, case_id, claim_id)
    references public.claims (owner_id, case_id, id) on delete set null,
  constraint forecasts_target_nonblank_ck check (btrim(target) <> ''),
  constraint forecasts_target_length_ck check (char_length(target) <= 10000),
  constraint forecasts_horizon_nonblank_ck check (btrim(horizon) <> ''),
  constraint forecasts_horizon_length_ck check (char_length(horizon) <= 500),
  constraint forecasts_probability_ck check (probability between 0 and 1),
  constraint forecasts_rationale_length_ck check (char_length(rationale) <= 20000),
  constraint forecasts_outcome_object_ck check (jsonb_typeof(outcome) = 'object'),
  constraint forecasts_status_ck check (status in ('draft', 'active', 'resolved', 'cancelled', 'expired')),
  constraint forecasts_provenance_object_ck check (jsonb_typeof(provenance) = 'object'),
  constraint forecasts_lifecycle_status_ck check (lifecycle_status in ('active', 'superseded', 'archived')),
  constraint forecasts_owner_id_unique unique (owner_id, id),
  constraint forecasts_owner_case_id_unique unique (owner_id, case_id, id)
);

create table if not exists public.tool_policies (
  id uuid primary key default gen_random_uuid(),
  owner_id uuid not null references auth.users(id) on delete cascade,
  case_id uuid,
  policy_name text not null,
  status text not null default 'draft',
  allowed_model_tiers text[] not null default array['luna', 'terra']::text[],
  allowed_tools text[] not null default '{}'::text[],
  per_run_token_budget integer not null default 20000,
  daily_token_budget integer,
  monthly_token_budget integer,
  per_run_cost_usd numeric(12, 4) not null default 1,
  daily_cost_usd numeric(12, 4),
  monthly_cost_usd numeric(12, 4),
  per_run_latency_ms integer not null default 60000,
  kill_switch boolean not null default false,
  external_writes_require_approval boolean not null default true,
  provenance jsonb not null default '{}'::jsonb,
  lifecycle_status text not null default 'active',
  created_by uuid not null references auth.users(id),
  updated_by uuid not null references auth.users(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint tool_policies_case_fk foreign key (owner_id, case_id)
    references public.cases (owner_id, id) on delete cascade,
  constraint tool_policies_name_nonblank_ck check (btrim(policy_name) <> ''),
  constraint tool_policies_name_length_ck check (char_length(policy_name) <= 300),
  constraint tool_policies_status_ck check (status in ('draft', 'active', 'disabled', 'archived')),
  constraint tool_policies_model_tiers_ck check (
    cardinality(allowed_model_tiers) between 1 and 4
    and array_position(allowed_model_tiers, null) is null
    and allowed_model_tiers <@ array['luna', 'terra', 'sol', 'pro']::text[]
  ),
  constraint tool_policies_tools_no_null_ck check (array_position(allowed_tools, null) is null and cardinality(allowed_tools) <= 200),
  constraint tool_policies_run_tokens_ck check (per_run_token_budget between 1 and 10000000),
  constraint tool_policies_daily_tokens_ck check (daily_token_budget is null or daily_token_budget between 1 and 100000000),
  constraint tool_policies_monthly_tokens_ck check (monthly_token_budget is null or monthly_token_budget between 1 and 1000000000),
  constraint tool_policies_run_cost_ck check (per_run_cost_usd > 0),
  constraint tool_policies_daily_cost_ck check (daily_cost_usd is null or daily_cost_usd > 0),
  constraint tool_policies_monthly_cost_ck check (monthly_cost_usd is null or monthly_cost_usd > 0),
  constraint tool_policies_latency_ck check (per_run_latency_ms between 1000 and 3600000),
  constraint tool_policies_external_approval_ck check (external_writes_require_approval),
  constraint tool_policies_provenance_object_ck check (jsonb_typeof(provenance) = 'object'),
  constraint tool_policies_lifecycle_status_ck check (lifecycle_status in ('active', 'archived')),
  constraint tool_policies_owner_id_unique unique (owner_id, id)
);

create table if not exists public.connector_accounts (
  id uuid primary key default gen_random_uuid(),
  owner_id uuid not null references auth.users(id) on delete cascade,
  provider text not null,
  display_name text not null,
  status text not null default 'pending_review',
  schema_version text not null default '1',
  secret_ref text not null default '',
  capabilities text[] not null default '{}'::text[],
  metadata jsonb not null default '{}'::jsonb,
  last_validated_at timestamptz,
  provenance jsonb not null default '{}'::jsonb,
  lifecycle_status text not null default 'active',
  created_by uuid not null references auth.users(id),
  updated_by uuid not null references auth.users(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint connector_accounts_provider_nonblank_ck check (btrim(provider) <> ''),
  constraint connector_accounts_provider_length_ck check (char_length(provider) <= 200),
  constraint connector_accounts_display_name_nonblank_ck check (btrim(display_name) <> ''),
  constraint connector_accounts_display_name_length_ck check (char_length(display_name) <= 300),
  constraint connector_accounts_status_ck check (status in ('active', 'disabled', 'revoked', 'pending_review', 'archived')),
  constraint connector_accounts_schema_version_nonblank_ck check (btrim(schema_version) <> '' and char_length(schema_version) <= 200),
  constraint connector_accounts_secret_ref_length_ck check (char_length(secret_ref) <= 500),
  constraint connector_accounts_capabilities_ck check (array_position(capabilities, null) is null and cardinality(capabilities) <= 200),
  constraint connector_accounts_metadata_object_ck check (jsonb_typeof(metadata) = 'object'),
  constraint connector_accounts_provenance_object_ck check (jsonb_typeof(provenance) = 'object'),
  constraint connector_accounts_lifecycle_status_ck check (lifecycle_status in ('active', 'archived')),
  constraint connector_accounts_owner_id_unique unique (owner_id, id)
);

create table if not exists public.connector_tools (
  id uuid primary key default gen_random_uuid(),
  owner_id uuid not null references auth.users(id) on delete cascade,
  connector_account_id uuid not null,
  tool_name text not null,
  schema_version text not null,
  operation_class text not null,
  input_schema jsonb not null default '{}'::jsonb,
  output_schema jsonb not null default '{}'::jsonb,
  status text not null default 'active',
  requires_approval boolean not null default true,
  provenance jsonb not null default '{}'::jsonb,
  lifecycle_status text not null default 'active',
  created_by uuid not null references auth.users(id),
  updated_by uuid not null references auth.users(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint connector_tools_account_fk foreign key (owner_id, connector_account_id)
    references public.connector_accounts (owner_id, id) on delete cascade,
  constraint connector_tools_tool_name_nonblank_ck check (btrim(tool_name) <> ''),
  constraint connector_tools_tool_name_length_ck check (char_length(tool_name) <= 300),
  constraint connector_tools_schema_version_nonblank_ck check (btrim(schema_version) <> '' and char_length(schema_version) <= 200),
  constraint connector_tools_operation_class_ck check (operation_class in ('read_only', 'evidence_write', 'canonical_write', 'external_write', 'archive_change')),
  constraint connector_tools_schema_objects_ck check (jsonb_typeof(input_schema) = 'object' and jsonb_typeof(output_schema) = 'object'),
  constraint connector_tools_approval_ck check (
    requires_approval or operation_class = 'read_only'
  ),
  constraint connector_tools_status_ck check (status in ('active', 'disabled', 'pending_review', 'archived')),
  constraint connector_tools_provenance_object_ck check (jsonb_typeof(provenance) = 'object'),
  constraint connector_tools_lifecycle_status_ck check (lifecycle_status in ('active', 'archived')),
  constraint connector_tools_owner_id_unique unique (owner_id, id),
  constraint connector_tools_account_name_unique unique (owner_id, connector_account_id, tool_name)
);

create table if not exists public.agent_runs (
  id uuid primary key default gen_random_uuid(),
  owner_id uuid not null references auth.users(id) on delete cascade,
  case_id uuid not null,
  tool_policy_id uuid,
  idempotency_key text not null,
  request_hash text not null,
  objective text not null,
  input_snapshot jsonb not null,
  input_snapshot_hash text not null,
  agent_graph jsonb not null default '{}'::jsonb,
  agent_config jsonb not null default '{}'::jsonb,
  prompt_version text not null,
  tool_allowlist text[] not null default '{}'::text[],
  model_tier text not null default 'terra',
  status text not null default 'queued',
  lifecycle_status text not null default 'active',
  retention_class text not null default 'standard',
  retention_until timestamptz,
  budget_tokens integer not null default 20000,
  budget_cost_usd numeric(12, 4) not null default 1,
  budget_latency_ms integer not null default 60000,
  budget_tool_events integer not null default 50,
  tokens_used integer not null default 0,
  cost_usd numeric(12, 4) not null default 0,
  latency_ms integer not null default 0,
  tool_events_count integer not null default 0,
  started_at timestamptz,
  completed_at timestamptz,
  cancel_requested_at timestamptz,
  cancel_requested_by uuid references auth.users(id),
  failure_code text,
  failure_message text,
  last_step_number integer not null default 0,
  last_idempotency_key text,
  last_transition_from text,
  last_transition_to text,
  last_transition_at timestamptz,
  provenance jsonb not null default '{}'::jsonb,
  created_by uuid not null references auth.users(id),
  updated_by uuid not null references auth.users(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint agent_runs_case_fk foreign key (owner_id, case_id)
    references public.cases (owner_id, id) on delete cascade,
  constraint agent_runs_policy_fk foreign key (owner_id, tool_policy_id)
    references public.tool_policies (owner_id, id) on delete set null,
  constraint agent_runs_idempotency_nonblank_ck check (btrim(idempotency_key) <> '' and char_length(idempotency_key) <= 300),
  constraint agent_runs_request_hash_ck check (request_hash ~ '^[0-9a-fA-F]{32}$'),
  constraint agent_runs_objective_nonblank_ck check (btrim(objective) <> ''),
  constraint agent_runs_objective_length_ck check (char_length(objective) <= 20000),
  constraint agent_runs_input_snapshot_object_ck check (jsonb_typeof(input_snapshot) = 'object'),
  constraint agent_runs_input_snapshot_hash_ck check (input_snapshot_hash ~ '^[0-9a-fA-F]{32}$'),
  constraint agent_runs_graph_object_ck check (jsonb_typeof(agent_graph) = 'object'),
  constraint agent_runs_config_object_ck check (jsonb_typeof(agent_config) = 'object'),
  constraint agent_runs_prompt_version_ck check (btrim(prompt_version) <> '' and char_length(prompt_version) <= 200),
  constraint agent_runs_tool_allowlist_ck check (array_position(tool_allowlist, null) is null and cardinality(tool_allowlist) <= 200),
  constraint agent_runs_model_tier_ck check (model_tier in ('luna', 'terra', 'sol', 'pro')),
  constraint agent_runs_status_ck check (status in ('queued', 'retrieving', 'synthesizing', 'awaiting_approval', 'executing', 'verifying', 'completed', 'blocked', 'failed', 'expired', 'budget_stopped', 'cancelled')),
  constraint agent_runs_lifecycle_status_ck check (lifecycle_status in ('active', 'archived')),
  constraint agent_runs_retention_class_ck check (retention_class in ('short', 'standard', 'long', 'legal_hold')),
  constraint agent_runs_budget_tokens_ck check (budget_tokens between 1 and 10000000),
  constraint agent_runs_budget_cost_ck check (budget_cost_usd > 0),
  constraint agent_runs_budget_latency_ck check (budget_latency_ms between 1000 and 3600000),
  constraint agent_runs_budget_tools_ck check (budget_tool_events between 1 and 10000),
  constraint agent_runs_usage_ck check (tokens_used >= 0 and cost_usd >= 0 and latency_ms >= 0 and tool_events_count >= 0 and last_step_number >= 0),
  constraint agent_runs_failure_length_ck check (failure_code is null or char_length(failure_code) <= 200),
  constraint agent_runs_failure_message_ck check (failure_message is null or char_length(failure_message) <= 5000),
  constraint agent_runs_provenance_object_ck check (jsonb_typeof(provenance) = 'object'),
  constraint agent_runs_owner_id_unique unique (owner_id, id),
  constraint agent_runs_owner_case_id_unique unique (owner_id, case_id, id),
  constraint agent_runs_owner_idempotency_unique unique (owner_id, idempotency_key)
);

create table if not exists public.agent_steps (
  id uuid primary key default gen_random_uuid(),
  owner_id uuid not null references auth.users(id) on delete cascade,
  case_id uuid not null,
  run_id uuid not null,
  sequence_no integer not null,
  step_kind text not null,
  status text not null default 'running',
  idempotency_key text not null,
  model_tier text not null,
  prompt_version text not null,
  input_payload jsonb not null default '{}'::jsonb,
  output_payload jsonb not null default '{}'::jsonb,
  tokens_used integer not null default 0,
  cost_usd numeric(12, 4) not null default 0,
  latency_ms integer not null default 0,
  failure_code text,
  failure_message text,
  provenance jsonb not null default '{}'::jsonb,
  lifecycle_status text not null default 'active',
  started_at timestamptz not null default now(),
  completed_at timestamptz,
  created_by uuid not null references auth.users(id),
  updated_by uuid not null references auth.users(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint agent_steps_run_fk foreign key (owner_id, case_id, run_id)
    references public.agent_runs (owner_id, case_id, id) on delete cascade,
  constraint agent_steps_sequence_ck check (sequence_no > 0),
  constraint agent_steps_kind_ck check (step_kind in ('retrieve', 'extract', 'synthesize', 'approval', 'execute', 'verify')),
  constraint agent_steps_status_ck check (status in ('running', 'completed', 'failed', 'blocked', 'skipped')),
  constraint agent_steps_idempotency_ck check (btrim(idempotency_key) <> '' and char_length(idempotency_key) <= 300),
  constraint agent_steps_model_tier_ck check (model_tier in ('luna', 'terra', 'sol', 'pro')),
  constraint agent_steps_prompt_version_ck check (btrim(prompt_version) <> '' and char_length(prompt_version) <= 200),
  constraint agent_steps_input_object_ck check (jsonb_typeof(input_payload) = 'object' and pg_column_size(input_payload) <= 1048576),
  constraint agent_steps_output_object_ck check (jsonb_typeof(output_payload) = 'object' and pg_column_size(output_payload) <= 1048576),
  constraint agent_steps_usage_ck check (tokens_used >= 0 and cost_usd >= 0 and latency_ms >= 0),
  constraint agent_steps_failure_length_ck check (failure_code is null or char_length(failure_code) <= 200),
  constraint agent_steps_failure_message_ck check (failure_message is null or char_length(failure_message) <= 5000),
  constraint agent_steps_provenance_object_ck check (jsonb_typeof(provenance) = 'object'),
  constraint agent_steps_lifecycle_status_ck check (lifecycle_status in ('active', 'archived')),
  constraint agent_steps_owner_id_unique unique (owner_id, id),
  constraint agent_steps_owner_case_id_unique unique (owner_id, case_id, id),
  constraint agent_steps_run_sequence_unique unique (owner_id, case_id, run_id, sequence_no),
  constraint agent_steps_run_idempotency_unique unique (owner_id, case_id, run_id, idempotency_key)
);

create table if not exists public.approval_requests (
  id uuid primary key default gen_random_uuid(),
  owner_id uuid not null references auth.users(id) on delete cascade,
  case_id uuid not null,
  run_id uuid,
  idempotency_key text not null,
  response_idempotency_key text,
  approval_kind text not null,
  status text not null default 'pending',
  title text not null,
  rationale text not null default '',
  proposed_diff jsonb not null,
  tool_action jsonb not null,
  exact_action_hash text not null,
  requested_by uuid not null references auth.users(id),
  responded_by uuid references auth.users(id),
  response_note text,
  requested_at timestamptz not null default now(),
  responded_at timestamptz,
  expires_at timestamptz,
  provenance jsonb not null default '{}'::jsonb,
  lifecycle_status text not null default 'active',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint approval_requests_case_fk foreign key (owner_id, case_id)
    references public.cases (owner_id, id) on delete cascade,
  constraint approval_requests_run_fk foreign key (owner_id, case_id, run_id)
    references public.agent_runs (owner_id, case_id, id) on delete cascade,
  constraint approval_requests_idempotency_ck check (btrim(idempotency_key) <> '' and char_length(idempotency_key) <= 300),
  constraint approval_requests_response_idempotency_ck check (response_idempotency_key is null or (btrim(response_idempotency_key) <> '' and char_length(response_idempotency_key) <= 300)),
  constraint approval_requests_kind_ck check (approval_kind in ('tool_action', 'canonical_write', 'external_write', 'archive_change')),
  constraint approval_requests_status_ck check (status in ('pending', 'approved', 'rejected', 'expired', 'cancelled')),
  constraint approval_requests_title_nonblank_ck check (btrim(title) <> ''),
  constraint approval_requests_title_length_ck check (char_length(title) <= 500),
  constraint approval_requests_rationale_length_ck check (char_length(rationale) <= 20000),
  constraint approval_requests_diff_object_ck check (jsonb_typeof(proposed_diff) = 'object' and pg_column_size(proposed_diff) <= 1048576),
  constraint approval_requests_tool_action_object_ck check (jsonb_typeof(tool_action) = 'object' and pg_column_size(tool_action) <= 1048576),
  constraint approval_requests_hash_ck check (exact_action_hash ~ '^[0-9a-fA-F]{32}$'),
  constraint approval_requests_response_note_length_ck check (response_note is null or char_length(response_note) <= 10000),
  constraint approval_requests_provenance_object_ck check (jsonb_typeof(provenance) = 'object'),
  constraint approval_requests_lifecycle_status_ck check (lifecycle_status in ('active', 'archived')),
  constraint approval_requests_owner_id_unique unique (owner_id, id),
  constraint approval_requests_owner_case_id_unique unique (owner_id, case_id, id),
  constraint approval_requests_owner_idempotency_unique unique (owner_id, case_id, idempotency_key)
);

create table if not exists public.change_proposals (
  id uuid primary key default gen_random_uuid(),
  owner_id uuid not null references auth.users(id) on delete cascade,
  case_id uuid not null,
  run_id uuid,
  approval_request_id uuid,
  idempotency_key text not null,
  target_type text not null,
  target_id uuid,
  operation text not null,
  before_snapshot jsonb not null default '{}'::jsonb,
  proposed_diff jsonb not null,
  after_snapshot jsonb not null default '{}'::jsonb,
  status text not null default 'pending',
  rationale text not null default '',
  provenance jsonb not null default '{}'::jsonb,
  lifecycle_status text not null default 'active',
  created_by uuid not null references auth.users(id),
  updated_by uuid not null references auth.users(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint change_proposals_case_fk foreign key (owner_id, case_id)
    references public.cases (owner_id, id) on delete cascade,
  constraint change_proposals_run_fk foreign key (owner_id, case_id, run_id)
    references public.agent_runs (owner_id, case_id, id) on delete cascade,
  constraint change_proposals_approval_fk foreign key (owner_id, case_id, approval_request_id)
    references public.approval_requests (owner_id, case_id, id) on delete set null,
  constraint change_proposals_idempotency_ck check (btrim(idempotency_key) <> '' and char_length(idempotency_key) <= 300),
  constraint change_proposals_target_type_ck check (target_type in ('record', 'claim', 'evidence_item', 'action', 'finding', 'entity', 'relation', 'decision_review', 'forecast')),
  constraint change_proposals_operation_ck check (operation in ('insert', 'update', 'delete', 'archive')),
  constraint change_proposals_before_object_ck check (jsonb_typeof(before_snapshot) = 'object' and pg_column_size(before_snapshot) <= 1048576),
  constraint change_proposals_diff_object_ck check (jsonb_typeof(proposed_diff) = 'object' and pg_column_size(proposed_diff) <= 1048576),
  constraint change_proposals_after_object_ck check (jsonb_typeof(after_snapshot) = 'object' and pg_column_size(after_snapshot) <= 1048576),
  constraint change_proposals_status_ck check (status in ('pending', 'approved', 'applied', 'rejected', 'expired', 'cancelled')),
  constraint change_proposals_rationale_length_ck check (char_length(rationale) <= 20000),
  constraint change_proposals_provenance_object_ck check (jsonb_typeof(provenance) = 'object'),
  constraint change_proposals_lifecycle_status_ck check (lifecycle_status in ('active', 'archived')),
  constraint change_proposals_owner_id_unique unique (owner_id, id),
  constraint change_proposals_owner_case_id_unique unique (owner_id, case_id, id),
  constraint change_proposals_owner_idempotency_unique unique (owner_id, case_id, idempotency_key)
);

create table if not exists public.tool_events (
  id uuid primary key default gen_random_uuid(),
  owner_id uuid not null references auth.users(id) on delete cascade,
  case_id uuid not null,
  run_id uuid not null,
  agent_step_id uuid,
  approval_request_id uuid,
  idempotency_key text not null,
  tool_name text not null,
  event_kind text not null,
  operation_class text not null,
  input_payload jsonb not null default '{}'::jsonb,
  output_payload jsonb not null default '{}'::jsonb,
  external_target text not null default '',
  provenance jsonb not null default '{}'::jsonb,
  lifecycle_status text not null default 'active',
  created_by uuid not null references auth.users(id),
  updated_by uuid not null references auth.users(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint tool_events_run_fk foreign key (owner_id, case_id, run_id)
    references public.agent_runs (owner_id, case_id, id) on delete cascade,
  constraint tool_events_step_fk foreign key (owner_id, case_id, agent_step_id)
    references public.agent_steps (owner_id, case_id, id) on delete set null,
  constraint tool_events_approval_fk foreign key (owner_id, case_id, approval_request_id)
    references public.approval_requests (owner_id, case_id, id) on delete set null,
  constraint tool_events_idempotency_ck check (btrim(idempotency_key) <> '' and char_length(idempotency_key) <= 300),
  constraint tool_events_tool_name_nonblank_ck check (btrim(tool_name) <> '' and char_length(tool_name) <= 300),
  constraint tool_events_kind_ck check (event_kind in ('requested', 'started', 'succeeded', 'failed', 'denied', 'skipped', 'approval_required')),
  constraint tool_events_operation_class_ck check (operation_class in ('read_only', 'evidence_write', 'canonical_write', 'external_write', 'archive_change')),
  constraint tool_events_input_object_ck check (jsonb_typeof(input_payload) = 'object' and pg_column_size(input_payload) <= 1048576),
  constraint tool_events_output_object_ck check (jsonb_typeof(output_payload) = 'object' and pg_column_size(output_payload) <= 1048576),
  constraint tool_events_external_target_length_ck check (char_length(external_target) <= 2000),
  constraint tool_events_provenance_object_ck check (jsonb_typeof(provenance) = 'object'),
  constraint tool_events_lifecycle_status_ck check (lifecycle_status in ('active', 'archived')),
  constraint tool_events_owner_id_unique unique (owner_id, id),
  constraint tool_events_owner_case_id_unique unique (owner_id, case_id, id),
  constraint tool_events_run_idempotency_unique unique (owner_id, case_id, run_id, idempotency_key)
);

create table if not exists public.automation_rules (
  id uuid primary key default gen_random_uuid(),
  owner_id uuid not null references auth.users(id) on delete cascade,
  case_id uuid not null,
  connector_account_id uuid,
  tool_policy_id uuid,
  rule_name text not null,
  trigger_type text not null,
  status text not null default 'draft',
  condition jsonb not null default '{}'::jsonb,
  action_config jsonb not null default '{}'::jsonb,
  output_kinds text[] not null default array['evidence']::text[],
  can_mutate_canonical boolean not null default false,
  connector_schema_version text,
  review_required boolean not null default false,
  disabled_reason text,
  provenance jsonb not null default '{}'::jsonb,
  lifecycle_status text not null default 'active',
  created_by uuid not null references auth.users(id),
  updated_by uuid not null references auth.users(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint automation_rules_case_fk foreign key (owner_id, case_id)
    references public.cases (owner_id, id) on delete cascade,
  constraint automation_rules_connector_fk foreign key (owner_id, connector_account_id)
    references public.connector_accounts (owner_id, id) on delete set null,
  constraint automation_rules_policy_fk foreign key (owner_id, tool_policy_id)
    references public.tool_policies (owner_id, id) on delete set null,
  constraint automation_rules_name_nonblank_ck check (btrim(rule_name) <> ''),
  constraint automation_rules_name_length_ck check (char_length(rule_name) <= 300),
  constraint automation_rules_trigger_type_ck check (trigger_type in ('schedule', 'record_created', 'evidence_added', 'manual', 'connector_event', 'webhook')),
  constraint automation_rules_status_ck check (status in ('draft', 'active', 'paused', 'disabled', 'pending_review', 'archived')),
  constraint automation_rules_condition_object_ck check (jsonb_typeof(condition) = 'object' and pg_column_size(condition) <= 1048576),
  constraint automation_rules_action_object_ck check (jsonb_typeof(action_config) = 'object' and pg_column_size(action_config) <= 1048576),
  constraint automation_rules_output_kinds_ck check (
    cardinality(output_kinds) between 1 and 3
    and array_position(output_kinds, null) is null
    and output_kinds <@ array['evidence', 'brief', 'approval']::text[]
  ),
  constraint automation_rules_no_canonical_mutation_ck check (not can_mutate_canonical),
  constraint automation_rules_connector_version_length_ck check (connector_schema_version is null or char_length(connector_schema_version) <= 200),
  constraint automation_rules_disabled_reason_length_ck check (disabled_reason is null or char_length(disabled_reason) <= 2000),
  constraint automation_rules_provenance_object_ck check (jsonb_typeof(provenance) = 'object'),
  constraint automation_rules_lifecycle_status_ck check (lifecycle_status in ('active', 'archived')),
  constraint automation_rules_owner_id_unique unique (owner_id, id),
  constraint automation_rules_owner_case_id_unique unique (owner_id, case_id, id),
  constraint automation_rules_owner_name_unique unique (owner_id, case_id, rule_name)
);

create table if not exists public.automation_runs (
  id uuid primary key default gen_random_uuid(),
  owner_id uuid not null references auth.users(id) on delete cascade,
  case_id uuid not null,
  rule_id uuid not null,
  agent_run_id uuid,
  idempotency_key text not null,
  status text not null default 'queued',
  trigger_payload jsonb not null default '{}'::jsonb,
  input_snapshot jsonb not null default '{}'::jsonb,
  output_kind text,
  output_artifact_id uuid,
  output_idempotency_key text,
  error_code text,
  error_message text,
  provenance jsonb not null default '{}'::jsonb,
  lifecycle_status text not null default 'active',
  started_at timestamptz,
  completed_at timestamptz,
  created_by uuid not null references auth.users(id),
  updated_by uuid not null references auth.users(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint automation_runs_case_fk foreign key (owner_id, case_id)
    references public.cases (owner_id, id) on delete cascade,
  constraint automation_runs_rule_fk foreign key (owner_id, case_id, rule_id)
    references public.automation_rules (owner_id, case_id, id) on delete cascade,
  constraint automation_runs_agent_fk foreign key (owner_id, case_id, agent_run_id)
    references public.agent_runs (owner_id, case_id, id) on delete set null,
  constraint automation_runs_idempotency_ck check (btrim(idempotency_key) <> '' and char_length(idempotency_key) <= 300),
  constraint automation_runs_status_ck check (status in ('queued', 'running', 'completed', 'failed', 'blocked', 'cancelled', 'budget_stopped')),
  constraint automation_runs_trigger_object_ck check (jsonb_typeof(trigger_payload) = 'object' and pg_column_size(trigger_payload) <= 1048576),
  constraint automation_runs_input_object_ck check (jsonb_typeof(input_snapshot) = 'object' and pg_column_size(input_snapshot) <= 1048576),
  constraint automation_runs_output_kind_ck check (output_kind is null or output_kind in ('evidence', 'brief', 'approval')),
  constraint automation_runs_error_length_ck check (error_code is null or char_length(error_code) <= 200),
  constraint automation_runs_error_message_ck check (error_message is null or char_length(error_message) <= 5000),
  constraint automation_runs_provenance_object_ck check (jsonb_typeof(provenance) = 'object'),
  constraint automation_runs_lifecycle_status_ck check (lifecycle_status in ('active', 'archived')),
  constraint automation_runs_owner_id_unique unique (owner_id, id),
  constraint automation_runs_owner_case_id_unique unique (owner_id, case_id, id),
  constraint automation_runs_rule_idempotency_unique unique (owner_id, case_id, rule_id, idempotency_key)
);

create table if not exists public.audit_events (
  id uuid primary key default gen_random_uuid(),
  owner_id uuid not null references auth.users(id) on delete cascade,
  case_id uuid,
  run_id uuid,
  actor_type text not null,
  event_type text not null,
  action text not null,
  target_type text not null,
  target_id uuid,
  details jsonb not null default '{}'::jsonb,
  provenance jsonb not null default '{}'::jsonb,
  lifecycle_status text not null default 'active',
  created_by uuid not null references auth.users(id),
  updated_by uuid not null references auth.users(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint audit_events_case_fk foreign key (owner_id, case_id)
    references public.cases (owner_id, id) on delete cascade,
  constraint audit_events_run_fk foreign key (owner_id, case_id, run_id)
    references public.agent_runs (owner_id, case_id, id) on delete cascade,
  constraint audit_events_actor_type_ck check (actor_type in ('user', 'agent', 'automation', 'system')),
  constraint audit_events_event_type_ck check (event_type in ('created', 'updated', 'transitioned', 'approved', 'rejected', 'read', 'tool_called', 'budget_stopped', 'cancelled', 'schema_changed', 'error')),
  constraint audit_events_action_nonblank_ck check (btrim(action) <> '' and char_length(action) <= 300),
  constraint audit_events_target_type_ck check (btrim(target_type) <> '' and char_length(target_type) <= 200),
  constraint audit_events_details_object_ck check (jsonb_typeof(details) = 'object' and pg_column_size(details) <= 1048576),
  constraint audit_events_provenance_object_ck check (jsonb_typeof(provenance) = 'object'),
  constraint audit_events_lifecycle_status_ck check (lifecycle_status in ('active', 'archived')),
  constraint audit_events_owner_id_unique unique (owner_id, id)
);

create table if not exists public.record_embeddings (
  id uuid primary key default gen_random_uuid(),
  owner_id uuid not null references auth.users(id) on delete cascade,
  case_id uuid,
  record_id uuid not null,
  embedding_status text not null default 'not_opted_in',
  embedding_opt_in boolean not null default false,
  regenerable boolean not null default true,
  embedding_format text not null default 'float32_json',
  embedding jsonb,
  embedding_dimension integer,
  model text,
  model_version text,
  source_content_hash text not null,
  source_revision integer,
  provenance jsonb not null default '{}'::jsonb,
  lifecycle_status text not null default 'active',
  created_by uuid not null references auth.users(id),
  updated_by uuid not null references auth.users(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint record_embeddings_case_fk foreign key (owner_id, case_id)
    references public.cases (owner_id, id) on delete set null,
  constraint record_embeddings_record_fk foreign key (owner_id, record_id)
    references public.records (user_id, id) on delete cascade,
  constraint record_embeddings_status_ck check (embedding_status in ('not_opted_in', 'queued', 'active', 'stale', 'failed', 'deleted')),
  constraint record_embeddings_opt_in_ck check (embedding_opt_in or embedding is null),
  constraint record_embeddings_format_ck check (embedding_format in ('float32_json')),
  constraint record_embeddings_dimension_ck check (embedding_dimension is null or embedding_dimension between 1 and 8192),
  constraint record_embeddings_model_ck check (
    (embedding is null and model is null and model_version is null)
    or (embedding is not null and model is not null and btrim(model) <> '' and char_length(model) <= 300)
  ),
  constraint record_embeddings_hash_ck check (source_content_hash ~ '^[0-9a-fA-F]{16,128}$'),
  constraint record_embeddings_revision_ck check (source_revision is null or source_revision > 0),
  constraint record_embeddings_provenance_object_ck check (jsonb_typeof(provenance) = 'object'),
  constraint record_embeddings_lifecycle_status_ck check (lifecycle_status in ('active', 'archived')),
  constraint record_embeddings_owner_id_unique unique (owner_id, id),
  constraint record_embeddings_owner_record_model_hash_unique unique (owner_id, record_id, model, source_content_hash)
);
