-- Durable, owner-scoped admission control for OpenAI-backed Conversation
-- Excavation. The table is deliberately outside the public API schema.

create schema if not exists private;
revoke all on schema private from public;
revoke all on schema private from anon;

create table if not exists private.conversation_extraction_quota (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  accepted_at timestamptz not null default pg_catalog.clock_timestamp()
);

create index if not exists conversation_extraction_quota_user_accepted_idx
  on private.conversation_extraction_quota (user_id, accepted_at);

alter table private.conversation_extraction_quota enable row level security;

revoke all on table private.conversation_extraction_quota from public;
revoke all on sequence private.conversation_extraction_quota_id_seq from public;
grant usage on schema private to authenticated;
grant select, insert, delete on table private.conversation_extraction_quota to authenticated;
grant usage, select on sequence private.conversation_extraction_quota_id_seq to authenticated;

drop policy if exists conversation_extraction_quota_select_own on private.conversation_extraction_quota;
create policy conversation_extraction_quota_select_own
  on private.conversation_extraction_quota
  for select to authenticated
  using ((select auth.uid()) = user_id);

drop policy if exists conversation_extraction_quota_insert_own on private.conversation_extraction_quota;
create policy conversation_extraction_quota_insert_own
  on private.conversation_extraction_quota
  for insert to authenticated
  with check ((select auth.uid()) = user_id);

drop policy if exists conversation_extraction_quota_delete_own on private.conversation_extraction_quota;
create policy conversation_extraction_quota_delete_own
  on private.conversation_extraction_quota
  for delete to authenticated
  using ((select auth.uid()) = user_id);

create or replace function public.consume_conversation_extraction_quota()
returns jsonb
language plpgsql
security invoker
set search_path = ''
as $$
declare
  caller_id uuid := auth.uid();
  now_at timestamptz := pg_catalog.clock_timestamp();
  latest_at timestamptz;
  oldest_at timestamptz;
  accepted_count integer;
  retry_after_seconds integer;
begin
  if caller_id is null then
    raise exception 'authentication required' using errcode = '42501';
  end if;

  -- Serialize one user's admission decisions so concurrent browser requests
  -- cannot both pass the limit before either inserts its own row.
  perform pg_catalog.pg_advisory_xact_lock(
    pg_catalog.hashtextextended(caller_id::text, 0)
  );

  delete from private.conversation_extraction_quota
  where user_id = caller_id
    and accepted_at <= now_at - interval '1 hour';

  select count(*)::integer, max(accepted_at), min(accepted_at)
    into accepted_count, latest_at, oldest_at
  from private.conversation_extraction_quota
  where user_id = caller_id;

  if latest_at is not null and now_at - latest_at < interval '30 seconds' then
    retry_after_seconds := greatest(
      1,
      ceil(extract(epoch from (latest_at + interval '30 seconds' - now_at)))::integer
    );
    return pg_catalog.jsonb_build_object(
      'allowed', false,
      'remaining', greatest(0, 10 - accepted_count),
      'retryAfterSeconds', retry_after_seconds
    );
  end if;

  if accepted_count >= 10 then
    retry_after_seconds := greatest(
      1,
      ceil(extract(epoch from (oldest_at + interval '1 hour' - now_at)))::integer
    );
    return pg_catalog.jsonb_build_object(
      'allowed', false,
      'remaining', 0,
      'retryAfterSeconds', retry_after_seconds
    );
  end if;

  insert into private.conversation_extraction_quota (user_id, accepted_at)
  values (caller_id, now_at);

  return pg_catalog.jsonb_build_object(
    'allowed', true,
    'remaining', 9 - accepted_count,
    'retryAfterSeconds', 0
  );
end;
$$;

revoke execute on function public.consume_conversation_extraction_quota() from public;
revoke execute on function public.consume_conversation_extraction_quota() from anon;
grant execute on function public.consume_conversation_extraction_quota() to authenticated;
